-- Reconstrucción del grado 1 de Matemáticas.
-- Se borran las 21 filas anteriores (evidencias de andamio + ejercicios, varios
-- rotos) y se siembran las 39 evidencias REALES del MEN y los ejercicios nuevos.

do $$
declare v_subject uuid;
begin
  select id into v_subject from subjects where slug = 'matematicas';
  delete from exercises where evidence_id in (
    select le.id from learning_evidences le
    join dbas d on d.id = le.dba_id
    where d.subject_id = v_subject and d.grade = 1);
  delete from learning_evidences where dba_id in (
    select id from dbas where subject_id = v_subject and grade = 1);
end $$;

-- ===== DBA 1: 5 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'c09467eb-d9d9-46b3-b633-a2c744a267ca'::uuid, d.id, 1, 'Construye e interpreta representaciones pictóricas y diagramas para representar relaciones entre cantidades que se presentan en situaciones o fenómenos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'bb2cf034-3a1b-4b69-8cb4-7d1996b9533a'::uuid, d.id, 2, 'Explica cómo y por qué es posible hacer una operación (suma o resta) en relación con los usos de los números y el contexto en el cual se presentan.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '6bbb3963-9854-4706-aec1-803cbbd26114'::uuid, d.id, 3, 'Reconoce en sus actuaciones cotidianas posibilidades de uso de los números y las operaciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '4822c024-61e4-4bdf-997f-fe36b1d917b1'::uuid, d.id, 4, 'Interpreta y resuelve problemas de juntar, quitar y completar, que involucren la cantidad de elementos de una colección o la medida de magnitudes como longitud, peso, capacidad y duración.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '466447c4-5b5a-4216-879a-1d12386aa854'::uuid, d.id, 5, 'Utiliza las operaciones (suma y resta) para representar el cambio en una cantidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('6bbb3963-9854-4706-aec1-803cbbd26114'::uuid, 'multiple_choice', '¿Cuál de estos números dice CUÁNTOS hay?', '{"options":["5 manzanas en la mesa","El 10 de la camiseta","El piso 3 del edificio","El teléfono 315"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('6bbb3963-9854-4706-aec1-803cbbd26114'::uuid, 'multiple_choice', '¿Cuál de estos números indica un ORDEN?', '{"options":["Llegó de 2º en la carrera","Hay 2 perros","La bolsa pesa 2 kilos","El bus número 2"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('6bbb3963-9854-4706-aec1-803cbbd26114'::uuid, 'multiple_choice', '¿Cuál de estos números es una MEDIDA?', '{"options":["La cuerda mide 3 metros","Tengo 3 primos","Vivo en el piso 3","Mi camiseta es la 3"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('6bbb3963-9854-4706-aec1-803cbbd26114'::uuid, 'multiple_choice', 'El número de tu casa, ¿para qué sirve?', '{"options":["Para saber cuál casa es","Para contar las casas","Para medir la casa","Para pesar la casa"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('4822c024-61e4-4bdf-997f-fe36b1d917b1'::uuid, 'multiple_choice', 'Tienes 4 manzanas y regalas 1. ¿Cuántas te quedan?', '{"options":["3","5","2","4"],"correctIndex":0,"operation":"4 − 1 = ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('4822c024-61e4-4bdf-997f-fe36b1d917b1'::uuid, 'multiple_choice', 'Ana tiene 3 bombas y le regalan 2. ¿Cuántas tiene ahora?', '{"options":["5","1","6","4"],"correctIndex":0,"operation":"3 + 2 = ?"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('4822c024-61e4-4bdf-997f-fe36b1d917b1'::uuid, 'multiple_choice', 'Hay 6 galletas en el plato y te comes 2. ¿Cuántas quedan?', '{"options":["4","8","3","5"],"correctIndex":0,"operation":"6 − 2 = ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('4822c024-61e4-4bdf-997f-fe36b1d917b1'::uuid, 'multiple_choice', 'Tengo 3 lápices y quiero tener 7. ¿Cuántos me faltan?', '{"options":["4","10","3","5"],"correctIndex":0,"operation":"3 + ? = 7"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('466447c4-5b5a-4216-879a-1d12386aa854'::uuid, 'multiple_choice', 'En el bus iban 5 niños y se subieron 3 más. ¿Qué operación usas?', '{"options":["Una suma","Una resta","Ninguna, ya se sabe","Contar hacia atrás"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('466447c4-5b5a-4216-879a-1d12386aa854'::uuid, 'multiple_choice', 'De una caja con 9 crayolas se pierden 4. ¿Qué operación usas?', '{"options":["Una resta","Una suma","Ninguna, ya se sabe","Contar de 2 en 2"],"correctIndex":0}'::jsonb, 2);

-- ===== DBA 2: 5 evidencias, 12 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'c5ccbe44-8b4b-4340-b71d-41c0561722ce'::uuid, d.id, 1, 'Realiza conteos (de uno en uno, de dos en dos, etc.) iniciando en cualquier número.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '600a257b-baeb-4462-ae7d-4fd8136504db'::uuid, d.id, 2, 'Determina la cantidad de elementos de una colección agrupándolos de 1 en 1, de 2 en 2, de 5 en 5.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '7deb675e-8659-4317-a6e3-2575038c0580'::uuid, d.id, 3, 'Describe y resuelve situaciones variadas con las operaciones de suma y resta en problemas cuya estructura puede ser a + b = ?, a + ? = c, o ? + b = c.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '0a86fdb6-bc4e-4ba4-ba26-dbf7794672eb'::uuid, d.id, 4, 'Establece y argumenta conjeturas de los posibles resultados en una secuencia numérica.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '5ea5ab21-3766-4bc7-a2bc-c5b4903be5ad'::uuid, d.id, 5, 'Utiliza las características del sistema decimal de numeración para crear estrategias de cálculo y estimación de sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5ccbe44-8b4b-4340-b71d-41c0561722ce'::uuid, 'multiple_choice', 'Cuenta de 2 en 2. ¿Qué número sigue?', '{"options":["10","9","12","7"],"correctIndex":0,"operation":"4, 6, 8, ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5ccbe44-8b4b-4340-b71d-41c0561722ce'::uuid, 'multiple_choice', 'Cuenta de 5 en 5. ¿Qué número sigue?', '{"options":["20","16","25","18"],"correctIndex":0,"operation":"5, 10, 15, ?"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5ccbe44-8b4b-4340-b71d-41c0561722ce'::uuid, 'multiple_choice', 'Cuenta de 1 en 1. ¿Qué número sigue?', '{"options":["10","11","6","12"],"correctIndex":0,"operation":"7, 8, 9, ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5ccbe44-8b4b-4340-b71d-41c0561722ce'::uuid, 'multiple_choice', 'Cuenta de 10 en 10. ¿Qué número sigue?', '{"options":["40","31","50","35"],"correctIndex":0,"operation":"10, 20, 30, ?"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('600a257b-baeb-4462-ae7d-4fd8136504db'::uuid, 'multiple_choice', 'Hay 4 pares de medias. ¿Cuántas medias hay en total?', '{"options":["8","6","4","10"],"correctIndex":0,"operation":"4 grupos de 2"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('600a257b-baeb-4462-ae7d-4fd8136504db'::uuid, 'multiple_choice', 'Tres manos abiertas. ¿Cuántos dedos hay en total?', '{"options":["15","8","10","20"],"correctIndex":0,"operation":"3 grupos de 5"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('7deb675e-8659-4317-a6e3-2575038c0580'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["8","2","7","9"],"correctIndex":0,"operation":"5 + 3 = ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('7deb675e-8659-4317-a6e3-2575038c0580'::uuid, 'multiple_choice', '¿Cuál es el número que falta?', '{"options":["7","11","6","8"],"correctIndex":0,"operation":"2 + ? = 9"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('7deb675e-8659-4317-a6e3-2575038c0580'::uuid, 'multiple_choice', '¿Cuál es el número que falta?', '{"options":["6","14","5","7"],"correctIndex":0,"operation":"? + 4 = 10"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('7deb675e-8659-4317-a6e3-2575038c0580'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["6","12","5","7"],"correctIndex":0,"operation":"9 − 3 = ?"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0a86fdb6-bc4e-4ba4-ba26-dbf7794672eb'::uuid, 'multiple_choice', 'En la secuencia 2, 4, 6, 8... los números son:', '{"options":["Siempre pares","Siempre impares","Unos pares y otros impares","Siempre mayores que 10"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('5ea5ab21-3766-4bc7-a2bc-c5b4903be5ad'::uuid, 'multiple_choice', 'Para calcular 9 + 6 más fácil, conviene pensar:', '{"options":["9 + 1 = 10, y 10 + 5 = 15","9 y 6 juntos son 96","Primero 6 − 9","9 + 10 = 19"],"correctIndex":0}'::jsonb, 1);

-- ===== DBA 3: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'c30ed2f4-46a2-4a8e-9329-31cbf05df273'::uuid, d.id, 1, 'Realiza composiciones y descomposiciones de números de dos dígitos en términos de la cantidad de "dieces" y de "unos" que los conforman.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select 'b3dc8d1c-cbb4-4ce1-a74c-6cfa1d0f4f00'::uuid, d.id, 2, 'Encuentra parejas de números que al adicionarse dan como resultado otro número dado.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select 'c5049ba8-ccfb-479e-b0cf-5c89e2da3d8d'::uuid, d.id, 3, 'Halla los números correspondientes a tener "diez más" o "diez menos" que una cantidad determinada.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select '30edf0d2-5c0d-431c-b9b3-7824e3003dc1'::uuid, d.id, 4, 'Emplea estrategias de cálculo como "el paso por el diez" para realizar adiciones o sustracciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c30ed2f4-46a2-4a8e-9329-31cbf05df273'::uuid, 'multiple_choice', 'El número 34 tiene...', '{"options":["3 decenas y 4 unidades","4 decenas y 3 unidades","34 decenas","3 unidades y 4 decenas"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c30ed2f4-46a2-4a8e-9329-31cbf05df273'::uuid, 'multiple_choice', '¿Qué número tiene 5 decenas y 2 unidades?', '{"options":["52","25","502","7"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c30ed2f4-46a2-4a8e-9329-31cbf05df273'::uuid, 'multiple_choice', 'El número 70 tiene...', '{"options":["7 decenas y 0 unidades","0 decenas y 7 unidades","7 unidades","70 decenas"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b3dc8d1c-cbb4-4ce1-a74c-6cfa1d0f4f00'::uuid, 'multiple_choice', '¿Cuál pareja suma 10?', '{"options":["6 y 4","6 y 3","5 y 6","8 y 3"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b3dc8d1c-cbb4-4ce1-a74c-6cfa1d0f4f00'::uuid, 'multiple_choice', '¿Cuál pareja suma 20?', '{"options":["15 y 5","15 y 10","12 y 6","10 y 5"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5049ba8-ccfb-479e-b0cf-5c89e2da3d8d'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["35","26","15","45"],"correctIndex":0,"operation":"25 + 10 = ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5049ba8-ccfb-479e-b0cf-5c89e2da3d8d'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["30","39","50","20"],"correctIndex":0,"operation":"40 − 10 = ?"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('c5049ba8-ccfb-479e-b0cf-5c89e2da3d8d'::uuid, 'multiple_choice', 'Diez más que 63 es...', '{"options":["73","64","53","630"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('30edf0d2-5c0d-431c-b9b3-7824e3003dc1'::uuid, 'multiple_choice', 'Para calcular 8 + 5 pasando por el diez:', '{"options":["8 + 2 = 10, luego 10 + 3 = 13","8 y 5 juntos son 85","Primero 5 − 8","8 + 10 = 18"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('30edf0d2-5c0d-431c-b9b3-7824e3003dc1'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["13","12","14","11"],"correctIndex":0,"operation":"7 + 6 = ?"}'::jsonb, 2);

-- ===== DBA 4: 4 evidencias, 9 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'dd985382-d9c3-4a6e-b4a9-244e534c6b48'::uuid, d.id, 1, 'Identifica atributos que se pueden medir en los objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select 'b901dcab-1e9c-43f8-8aa7-7dab6c741d53'::uuid, d.id, 2, 'Diferencia atributos medibles (longitud, masa, capacidad, duración, cantidad de elementos de una colección), en términos de los instrumentos y las unidades utilizadas para medirlos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select '0fd1fbb8-5817-4f1f-a7bf-276e5c2a4c3a'::uuid, d.id, 3, 'Compara y ordena objetos de acuerdo con atributos como altura, peso, intensidades de color, entre otros y recorridos según la distancia de cada trayecto.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select '2d8dcce5-4263-411d-bd32-4b73a8b63612'::uuid, d.id, 4, 'Compara y ordena colecciones según la cantidad de elementos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('dd985382-d9c3-4a6e-b4a9-244e534c6b48'::uuid, 'multiple_choice', '¿Qué se puede MEDIR de una cuerda?', '{"options":["Su largo","Su color","Su nombre","Su dueño"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b901dcab-1e9c-43f8-8aa7-7dab6c741d53'::uuid, 'multiple_choice', '¿Con qué mides cuánto PESA una fruta?', '{"options":["Con una balanza","Con una regla","Con un reloj","Con un vaso"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b901dcab-1e9c-43f8-8aa7-7dab6c741d53'::uuid, 'multiple_choice', '¿Con qué mides cuánto DURA un juego?', '{"options":["Con un reloj","Con una regla","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b901dcab-1e9c-43f8-8aa7-7dab6c741d53'::uuid, 'multiple_choice', '¿Con qué mides cuánta agua CABE en una jarra?', '{"options":["Con un vaso medidor","Con una regla","Con un reloj","Con una balanza"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0fd1fbb8-5817-4f1f-a7bf-276e5c2a4c3a'::uuid, 'multiple_choice', 'Si los ordenas del más corto al más largo, ¿cuál va PRIMERO?', '{"options":["Un clip","Un lápiz","Una regla","Una escoba"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0fd1fbb8-5817-4f1f-a7bf-276e5c2a4c3a'::uuid, 'multiple_choice', '¿Cuál de estos pesa MÁS?', '{"options":["Un balde con agua","Un vaso con agua","Una cuchara con agua","Una gota de agua"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0fd1fbb8-5817-4f1f-a7bf-276e5c2a4c3a'::uuid, 'multiple_choice', 'En una carrera, ¿quién recorrió MÁS distancia?', '{"options":["Quien dio 30 pasos","Quien dio 20 pasos","Quien dio 10 pasos","Quien dio 5 pasos"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('2d8dcce5-4263-411d-bd32-4b73a8b63612'::uuid, 'multiple_choice', '¿Cuál grupo tiene MÁS elementos?', '{"options":["8 estrellas","5 estrellas","3 estrellas","6 estrellas"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('2d8dcce5-4263-411d-bd32-4b73a8b63612'::uuid, 'multiple_choice', '¿Cuál grupo tiene MENOS elementos?', '{"options":["2 flores","7 flores","5 flores","9 flores"],"correctIndex":0}'::jsonb, 2);

-- ===== DBA 5: 3 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'cacdfbb9-81cb-45cc-86ec-2449e8e3c0b9'::uuid, d.id, 1, 'Mide longitudes con diferentes instrumentos y expresa el resultado en unidades estandarizadas o no estandarizadas comunes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select 'caaf4530-573f-490e-ba3c-f283f539af52'::uuid, d.id, 2, 'Compara objetos a partir de su longitud, masa, capacidad y duración de eventos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select 'aaf9e65a-f293-4d96-9527-917495709ff2'::uuid, d.id, 3, 'Toma decisiones a partir de las mediciones realizadas y de acuerdo con los requerimientos del problema.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('cacdfbb9-81cb-45cc-86ec-2449e8e3c0b9'::uuid, 'multiple_choice', 'Un lápiz mide 3 clips y otro mide 5 clips. ¿Cuántos clips más largo es el segundo?', '{"options":["2","8","3","1"],"correctIndex":0,"operation":"5 − 3 = ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('cacdfbb9-81cb-45cc-86ec-2449e8e3c0b9'::uuid, 'multiple_choice', 'La mesa mide 4 cuartas. ¿Con qué la mediste?', '{"options":["Con tu mano","Con un reloj","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('cacdfbb9-81cb-45cc-86ec-2449e8e3c0b9'::uuid, 'multiple_choice', 'Si mides el salón con pasos GRANDES, necesitas...', '{"options":["Menos pasos","Más pasos","Los mismos pasos","Ningún paso"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('caaf4530-573f-490e-ba3c-f283f539af52'::uuid, 'multiple_choice', 'Una jarra llena 4 vasos y otra llena 7 vasos. ¿Cuál tiene MÁS capacidad?', '{"options":["La de 7 vasos","La de 4 vasos","Las dos igual","No se puede saber"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('caaf4530-573f-490e-ba3c-f283f539af52'::uuid, 'multiple_choice', '¿Cuál de estas cosas dura MÁS tiempo?', '{"options":["Una clase","Un parpadeo","Un estornudo","Un aplauso"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('caaf4530-573f-490e-ba3c-f283f539af52'::uuid, 'multiple_choice', 'Una cinta mide 8 clips y otra también mide 8 clips. Entonces...', '{"options":["Miden lo mismo","La primera es más larga","La segunda es más larga","No se pueden comparar"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('aaf9e65a-f293-4d96-9527-917495709ff2'::uuid, 'multiple_choice', 'El estante mide 6 cuartas y la caja mide 8 cuartas. ¿Cabe la caja?', '{"options":["No, la caja es más ancha","Sí, y sobra espacio","Sí, entra justo","No se puede saber"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('aaf9e65a-f293-4d96-9527-917495709ff2'::uuid, 'multiple_choice', 'Necesitas 10 clips de cinta y tienes 6. ¿Cuántos te faltan?', '{"options":["4","16","3","5"],"correctIndex":0,"operation":"6 + ? = 10"}'::jsonb, 2);

-- ===== DBA 6: 4 evidencias, 9 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '367e5a97-8840-4038-8e78-24da12012edf'::uuid, d.id, 1, 'Crea, compone y descompone formas bidimensionales y tridimensionales, para ello utiliza plastilina, papel, palitos, cajas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '98987dbe-8db7-4981-925e-9534ea8fde13'::uuid, d.id, 2, 'Describe de forma verbal las cualidades y propiedades de un objeto relativas a su forma.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select 'ab1a018c-acea-444d-bdfb-11589b3b9659'::uuid, d.id, 3, 'Agrupa objetos de su entorno de acuerdo con las semejanzas y las diferencias en la forma y en el tamaño y explica el criterio que utiliza.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select 'e3089302-827d-4226-9748-3d8a8d7b86ba'::uuid, d.id, 4, 'Identifica objetos a partir de las descripciones verbales que hacen de sus características geométricas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('98987dbe-8db7-4981-925e-9534ea8fde13'::uuid, 'multiple_choice', '¿Cuántos lados tiene un triángulo?', '{"options":["3","4","5","1"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('98987dbe-8db7-4981-925e-9534ea8fde13'::uuid, 'multiple_choice', '¿Cuántos lados tiene un cuadrado?', '{"options":["4","3","5","6"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('98987dbe-8db7-4981-925e-9534ea8fde13'::uuid, 'multiple_choice', '¿Cuál de estos bordes es CURVO?', '{"options":["El borde de un plato","El borde de una regla","El borde de una mesa","El borde de un libro"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e3089302-827d-4226-9748-3d8a8d7b86ba'::uuid, 'multiple_choice', 'Tiene 3 lados y 3 puntas. ¿Qué figura es?', '{"options":["Triángulo","Cuadrado","Círculo","Rectángulo"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e3089302-827d-4226-9748-3d8a8d7b86ba'::uuid, 'multiple_choice', 'Tiene 4 lados iguales y 4 puntas. ¿Qué figura es?', '{"options":["Cuadrado","Rectángulo","Triángulo","Círculo"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e3089302-827d-4226-9748-3d8a8d7b86ba'::uuid, 'multiple_choice', '¿Cuál figura NO tiene puntas?', '{"options":["Círculo","Triángulo","Cuadrado","Rectángulo"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('ab1a018c-acea-444d-bdfb-11589b3b9659'::uuid, 'multiple_choice', 'Una pelota de fútbol tiene forma de...', '{"options":["Esfera","Cubo","Cilindro","Pirámide"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('ab1a018c-acea-444d-bdfb-11589b3b9659'::uuid, 'multiple_choice', 'Un vaso y una lata tienen forma de...', '{"options":["Cilindro","Cubo","Esfera","Pirámide"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('ab1a018c-acea-444d-bdfb-11589b3b9659'::uuid, 'multiple_choice', 'Un dado tiene forma de...', '{"options":["Cubo","Esfera","Cono","Cilindro"],"correctIndex":0}'::jsonb, 3);

-- ===== DBA 7: 4 evidencias, 7 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'b61399e7-66e6-4812-a4af-942e1165a617'::uuid, d.id, 1, 'Utiliza representaciones como planos para ubicarse en el espacio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '9c7986c4-2a60-4cdc-bbaf-5100b1afa1e0'::uuid, d.id, 2, 'Toma decisiones a partir de la ubicación espacial.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '0ddf232b-4c89-429a-a499-6b15470b2915'::uuid, d.id, 3, 'Dibuja recorridos, para ello considera los ángulos y la lateralidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select 'a771a13d-1b47-4ff0-be95-a5c2d1d41bf7'::uuid, d.id, 4, 'Compara distancias a partir de la observación del plano al estimar con pasos, baldosas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('a771a13d-1b47-4ff0-be95-a5c2d1d41bf7'::uuid, 'multiple_choice', 'La tienda está a 10 pasos y el parque a 25 pasos. ¿Cuál queda MÁS CERCA?', '{"options":["La tienda","El parque","Están a la misma distancia","No se puede saber"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('a771a13d-1b47-4ff0-be95-a5c2d1d41bf7'::uuid, 'multiple_choice', '¿Cuál camino es MÁS LARGO?', '{"options":["30 baldosas","12 baldosas","8 baldosas","20 baldosas"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('a771a13d-1b47-4ff0-be95-a5c2d1d41bf7'::uuid, 'multiple_choice', 'Un camino de 3 cuadras es ___ que uno de 6 cuadras.', '{"options":["más corto","más largo","igual de largo","más ancho"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b61399e7-66e6-4812-a4af-942e1165a617'::uuid, 'multiple_choice', 'Si el perro está DEBAJO de la mesa, entonces la mesa está...', '{"options":["Encima del perro","Debajo del perro","Al lado del perro","Lejos del perro"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('b61399e7-66e6-4812-a4af-942e1165a617'::uuid, 'multiple_choice', 'En el plano del salón, el tablero está al frente y la puerta atrás. Si estás en la puerta, el tablero queda...', '{"options":["Al frente tuyo","Detrás tuyo","Debajo tuyo","Encima tuyo"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0ddf232b-4c89-429a-a499-6b15470b2915'::uuid, 'multiple_choice', 'Vas caminando y das media vuelta. Ahora caminas...', '{"options":["De regreso, por donde viniste","Hacia el mismo lado","Hacia arriba","Sin moverte"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('9c7986c4-2a60-4cdc-bbaf-5100b1afa1e0'::uuid, 'multiple_choice', '¿Cuál de estas indicaciones sirve para llegar a un lugar?', '{"options":["Camina 2 cuadras y gira a la izquierda","Camina un rato largo","Queda por ahí cerca","Es una casa bonita"],"correctIndex":0}'::jsonb, 1);

-- ===== DBA 8: 3 evidencias, 7 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '310f4670-6d7c-47bb-a125-f97531096610'::uuid, d.id, 1, 'Identifica y nombra diferencias entre objetos o grupos de objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select '0991f767-a7c3-4da7-aa14-7d135b748718'::uuid, d.id, 2, 'Comunica las características identificadas y justifica las diferencias que encuentra.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select '0959cf02-a855-4c2e-91a9-b41ac794a955'::uuid, d.id, 3, 'Establece relaciones de dependencia entre magnitudes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0959cf02-a855-4c2e-91a9-b41ac794a955'::uuid, 'multiple_choice', 'Si llenas más vasos desde la misma jarra, el agua que queda en la jarra...', '{"options":["Disminuye","Aumenta","Sigue igual","Se vuelve más pesada"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0959cf02-a855-4c2e-91a9-b41ac794a955'::uuid, 'multiple_choice', 'Mientras más alto crece un árbol, su tronco se ve...', '{"options":["Más largo","Más corto","Igual de largo","Más delgado"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0959cf02-a855-4c2e-91a9-b41ac794a955'::uuid, 'multiple_choice', 'Si caminas más rápido, llegas...', '{"options":["En menos tiempo","En más tiempo","En el mismo tiempo","Nunca llegas"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0959cf02-a855-4c2e-91a9-b41ac794a955'::uuid, 'multiple_choice', 'Mientras más personas suben al bus, los puestos libres...', '{"options":["Disminuyen","Aumentan","Siguen igual","Se duplican"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('310f4670-6d7c-47bb-a125-f97531096610'::uuid, 'multiple_choice', 'Un vaso tenía 2 canicas y ahora tiene 5. ¿Qué pasó?', '{"options":["Se agregaron canicas","Se quitaron canicas","No cambió nada","Se hicieron más grandes"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('310f4670-6d7c-47bb-a125-f97531096610'::uuid, 'multiple_choice', 'Tenías 10 dulces y ahora tienes 6. El cambio fue que...', '{"options":["Disminuyó en 4","Aumentó en 4","Disminuyó en 6","No cambió"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('0991f767-a7c3-4da7-aa14-7d135b748718'::uuid, 'multiple_choice', 'Un grupo tiene 3 patos y otro tiene 3 patos con sombrero. ¿En qué se diferencian?', '{"options":["En el sombrero","En la cantidad","En nada","En el color del agua"],"correctIndex":0}'::jsonb, 1);

-- ===== DBA 9: 3 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, d.id, 1, 'Propone números que satisfacen una igualdad con sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select 'ae94082c-59fb-494a-97e3-b370de5ef2f8'::uuid, d.id, 2, 'Describe las características de los números que deben ubicarse en una ecuación de tal manera que satisfaga la igualdad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select '14c61449-0b5f-46a3-88c5-040da3ee35e8'::uuid, d.id, 3, 'Argumenta sobre el uso de la propiedad transitiva en un conjunto de igualdades.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","5","6","3"],"correctIndex":0,"operation":"2 + 3 = 1 + ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["3","5","4","1"],"correctIndex":0,"operation":"4 + 1 = ? + 2"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","8","3","6"],"correctIndex":0,"operation":"6 = 2 + ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","10","3","18"],"correctIndex":0,"operation":"5 + 5 = 8 + ?"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","5","4","1"],"correctIndex":0,"operation":"7 − 2 = 3 + ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('e37d7d3e-c313-4825-89e4-fa7c5cf27d26'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","16","5","3"],"correctIndex":0,"operation":"10 = ? + 6"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('ae94082c-59fb-494a-97e3-b370de5ef2f8'::uuid, 'multiple_choice', 'El signo = quiere decir que...', '{"options":["Los dos lados valen lo mismo","Hay que sumar","Ahí sigue la respuesta","Un lado es mayor"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('14c61449-0b5f-46a3-88c5-040da3ee35e8'::uuid, 'multiple_choice', 'Si 3 + 4 = 7 y además 7 = 5 + 2, entonces 3 + 4 es igual a...', '{"options":["5 + 2","5 − 2","3 + 2","7 + 7"],"correctIndex":0}'::jsonb, 1);

-- ===== DBA 10: 4 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '7a751f7b-8e47-4cbc-ac6f-997df226a98f'::uuid, d.id, 1, 'Identifica en fichas u objetos reales los valores de la variable en estudio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '07e88327-3ebb-45ef-95a1-4c989e8c2ccf'::uuid, d.id, 2, 'Organiza los datos en tablas de conteo y/o en pictogramas sin escala.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select 'a8e87c74-4f94-4548-b261-f25fbdad7fe3'::uuid, d.id, 3, 'Lee la información presentada en tablas de conteo y/o pictogramas sin escala (1 a 1).' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select 'fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, d.id, 4, 'Comunica los resultados respondiendo preguntas tales como: ¿cuántos hay en total?, ¿cuántos hay de cada dato?, ¿cuál es el dato que más se repite?, ¿cuál es el dato que menos aparece?' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, 'multiple_choice', 'Color favorito del curso: Rojo 3, Azul 5, Verde 2. ¿Cuál ganó?', '{"options":["Azul","Rojo","Verde","Ninguno, hay empate"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, 'multiple_choice', 'Color favorito del curso: Rojo 3, Azul 5, Verde 2. ¿Cuál tuvo MENOS votos?', '{"options":["Verde","Rojo","Azul","Todos tuvieron igual"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, 'multiple_choice', 'Color favorito del curso: Rojo 3, Azul 5, Verde 2. ¿Cuántos niños votaron en total?', '{"options":["10","8","9","11"],"correctIndex":0,"operation":"3 + 5 + 2 = ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, 'multiple_choice', 'Fruta preferida: Mango 7, Banano 7, Papaya 2. ¿Cuál se repite más?', '{"options":["Mango y banano, empatados","Solo el mango","La papaya","Solo el banano"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('fc4f81cf-b00c-477a-8c5c-1c9eb42e4fc4'::uuid, 'multiple_choice', 'Fruta preferida: Mango 7, Banano 7, Papaya 2. ¿Cuántos MÁS prefieren mango que papaya?', '{"options":["5","9","4","2"],"correctIndex":0,"operation":"7 − 2 = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('a8e87c74-4f94-4548-b261-f25fbdad7fe3'::uuid, 'multiple_choice', 'En el pictograma, cada helado dibujado es 1 niño. Hay 4 helados de chocolate. ¿Cuántos niños lo prefieren?', '{"options":["4","3","5","8"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('a8e87c74-4f94-4548-b261-f25fbdad7fe3'::uuid, 'multiple_choice', 'Cada dibujo de perro vale 1 mascota. Hay 6 dibujos. Entonces hay...', '{"options":["6 perros","1 perro","12 perros","3 perros"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_evidence) values ('07e88327-3ebb-45ef-95a1-4c989e8c2ccf'::uuid, 'multiple_choice', 'En una tabla de conteo, las rayitas sirven para...', '{"options":["Contar cuántos hay de cada cosa","Dibujar la figura","Medir el largo","Decir la hora"],"correctIndex":0}'::jsonb, 1);

do $$
declare n_ev int; n_ex int; n_malas int;
begin
  select count(*) into n_ev from learning_evidences le join dbas d on d.id = le.dba_id
    join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1;
  select count(*) into n_ex from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1;
  -- Toda pregunta debe tener exactamente 4 opciones distintas entre sí.
  select count(*) into n_malas from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1 and (jsonb_array_length(e.config->'options') <> 4
      or (select count(distinct v) from jsonb_array_elements_text(e.config->'options') v) <> 4);
  if n_ev <> 39 then raise exception 'evidencias: % (esperadas 39)', n_ev; end if;
  if n_ex <> 88 then raise exception 'ejercicios: % (esperados 88)', n_ex; end if;
  if n_malas <> 0 then raise exception '% ejercicios sin 4 opciones distintas', n_malas; end if;
end $$;
