-- Revisión pedagógica del grado 1.
-- Las 39 evidencias del MEN no cambian. Cambia cómo está escrito cada
-- ejercicio (enunciado corto, opciones cortas, palabras de niño) y el ORDEN
-- dentro de cada lección: de lo concreto a lo abstracto.

-- El orden ya no lo manda el número de evidencia (una clasificación curricular,
-- no una rampa de dificultad) sino la posición dentro de la lección. La columna
-- pasa a llamarse por lo que de verdad significa.
do $$
begin
  if exists (select 1 from information_schema.columns
             where table_name = 'exercises' and column_name = 'order_in_evidence') then
    alter table exercises rename column order_in_evidence to order_in_lesson;
  end if;
end $$;

do $$
declare v_subject uuid;
begin
  select id into v_subject from subjects where slug = 'matematicas';
  delete from exercises where evidence_id in (
    select le.id from learning_evidences le
    join dbas d on d.id = le.dba_id
    where d.subject_id = v_subject and d.grade = 1);
  delete from learning_evidences where dba_id in (
    select id from dbas where subject_id = v_subject and grade = 1);
end $$;

-- ===== DBA 1: 5 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '7cd7d48c-4a2d-4dca-b470-16793ed2fa7a'::uuid, d.id, 1, 'Construye e interpreta representaciones pictóricas y diagramas para representar relaciones entre cantidades que se presentan en situaciones o fenómenos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '77f727ba-2f39-445a-bb18-fbba3cf16685'::uuid, d.id, 2, 'Explica cómo y por qué es posible hacer una operación (suma o resta) en relación con los usos de los números y el contexto en el cual se presentan.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'c49d681b-237e-4aeb-bf9e-958a99bf51c8'::uuid, d.id, 3, 'Reconoce en sus actuaciones cotidianas posibilidades de uso de los números y las operaciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'dd2faabc-4b09-4288-8cfd-c633e74b210e'::uuid, d.id, 4, 'Interpreta y resuelve problemas de juntar, quitar y completar, que involucren la cantidad de elementos de una colección o la medida de magnitudes como longitud, peso, capacidad y duración.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '27004a2d-57d5-4817-a675-944bb897f1a3'::uuid, d.id, 5, 'Utiliza las operaciones (suma y resta) para representar el cambio en una cantidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c49d681b-237e-4aeb-bf9e-958a99bf51c8'::uuid, 'multiple_choice', '¿Cuál número dice CUÁNTOS hay?', '{"options":["5 manzanas","El piso 3","El bus 20","El teléfono 315"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c49d681b-237e-4aeb-bf9e-958a99bf51c8'::uuid, 'multiple_choice', '¿Cuál número dice EN QUÉ PUESTO llegó?', '{"options":["Llegó de 2º","Tiene 2 perros","Mide 2 metros","Vive en la casa 2"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c49d681b-237e-4aeb-bf9e-958a99bf51c8'::uuid, 'multiple_choice', '¿Cuál número dice CUÁNTO MIDE?', '{"options":["Mide 3 metros","Tengo 3 primos","Vivo en el piso 3","Soy el número 3"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c49d681b-237e-4aeb-bf9e-958a99bf51c8'::uuid, 'multiple_choice', 'El número de tu casa sirve para:', '{"options":["Saber cuál casa es","Contar las casas","Medir la casa","Pesar la casa"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('dd2faabc-4b09-4288-8cfd-c633e74b210e'::uuid, 'multiple_choice', 'Ana tiene 3 bombas. Le regalan 2.', '{"options":["5","1","6","4"],"correctIndex":0,"operation":"3 + 2 = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('dd2faabc-4b09-4288-8cfd-c633e74b210e'::uuid, 'multiple_choice', 'Tienes 4 manzanas. Regalas 1.', '{"options":["3","5","2","4"],"correctIndex":0,"operation":"4 − 1 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('dd2faabc-4b09-4288-8cfd-c633e74b210e'::uuid, 'multiple_choice', 'Hay 6 galletas. Te comes 2.', '{"options":["4","8","3","5"],"correctIndex":0,"operation":"6 − 2 = ?"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('dd2faabc-4b09-4288-8cfd-c633e74b210e'::uuid, 'multiple_choice', 'Tengo 3 lápices. Quiero 7. ¿Cuántos faltan?', '{"options":["4","10","3","5"],"correctIndex":0,"operation":"3 + ? = 7"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('27004a2d-57d5-4817-a675-944bb897f1a3'::uuid, 'multiple_choice', 'Al bus se suben 3 niños. Para saber cuántos hay ahora:', '{"options":["Sumo","Resto","Cuento hacia atrás","No hago nada"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('27004a2d-57d5-4817-a675-944bb897f1a3'::uuid, 'multiple_choice', 'De la caja se pierden 4 crayolas. Para saber cuántas quedan:', '{"options":["Resto","Sumo","Cuento hacia adelante","No hago nada"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 2: 5 evidencias, 12 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '85fd0f3c-08c6-4a3c-a91b-4601cb8eb314'::uuid, d.id, 1, 'Realiza conteos (de uno en uno, de dos en dos, etc.) iniciando en cualquier número.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '455aa746-8a43-4572-adc9-62e57da4d384'::uuid, d.id, 2, 'Determina la cantidad de elementos de una colección agrupándolos de 1 en 1, de 2 en 2, de 5 en 5.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '459220cc-c30a-4fa8-9996-742c995d2d57'::uuid, d.id, 3, 'Describe y resuelve situaciones variadas con las operaciones de suma y resta en problemas cuya estructura puede ser a + b = ?, a + ? = c, o ? + b = c.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '7b5a07f5-a988-4fdd-9a46-2ed72a333831'::uuid, d.id, 4, 'Establece y argumenta conjeturas de los posibles resultados en una secuencia numérica.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select 'a5ad27ef-9acb-41ec-9c90-b34361668cd7'::uuid, d.id, 5, 'Utiliza las características del sistema decimal de numeración para crear estrategias de cálculo y estimación de sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('85fd0f3c-08c6-4a3c-a91b-4601cb8eb314'::uuid, 'multiple_choice', 'Cuenta de 1 en 1. ¿Qué sigue?', '{"options":["10","11","6","12"],"correctIndex":0,"operation":"7, 8, 9, ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('85fd0f3c-08c6-4a3c-a91b-4601cb8eb314'::uuid, 'multiple_choice', 'Cuenta de 2 en 2. ¿Qué sigue?', '{"options":["10","9","12","7"],"correctIndex":0,"operation":"4, 6, 8, ?"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('85fd0f3c-08c6-4a3c-a91b-4601cb8eb314'::uuid, 'multiple_choice', 'Cuenta de 5 en 5. ¿Qué sigue?', '{"options":["20","16","25","18"],"correctIndex":0,"operation":"5, 10, 15, ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('85fd0f3c-08c6-4a3c-a91b-4601cb8eb314'::uuid, 'multiple_choice', 'Cuenta de 10 en 10. ¿Qué sigue?', '{"options":["40","31","50","35"],"correctIndex":0,"operation":"10, 20, 30, ?"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('455aa746-8a43-4572-adc9-62e57da4d384'::uuid, 'multiple_choice', 'Hay 4 pares de medias. Cuéntalas de 2 en 2.', '{"options":["8","6","4","10"],"correctIndex":0,"operation":"2 + 2 + 2 + 2 = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('455aa746-8a43-4572-adc9-62e57da4d384'::uuid, 'multiple_choice', 'Tres manos abiertas. Cuenta de 5 en 5.', '{"options":["15","8","10","20"],"correctIndex":0,"operation":"5 + 5 + 5 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('459220cc-c30a-4fa8-9996-742c995d2d57'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["8","2","7","9"],"correctIndex":0,"operation":"5 + 3 = ?"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('459220cc-c30a-4fa8-9996-742c995d2d57'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["6","12","5","7"],"correctIndex":0,"operation":"9 − 3 = ?"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('459220cc-c30a-4fa8-9996-742c995d2d57'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["7","11","6","8"],"correctIndex":0,"operation":"2 + ? = 9"}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('459220cc-c30a-4fa8-9996-742c995d2d57'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["6","14","5","7"],"correctIndex":0,"operation":"? + 4 = 10"}'::jsonb, 10);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('a5ad27ef-9acb-41ec-9c90-b34361668cd7'::uuid, 'multiple_choice', '¿Cuánto le falta a 7 para llegar a 10?', '{"options":["3","4","17","2"],"correctIndex":0,"operation":"7 + ? = 10"}'::jsonb, 11);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7b5a07f5-a988-4fdd-9a46-2ed72a333831'::uuid, 'multiple_choice', 'En 2, 4, 6, 8... todos los números son:', '{"options":["Pares","Impares","Unos pares y otros no","Mayores que 10"],"correctIndex":0}'::jsonb, 12);

-- ===== DBA 3: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '988d365c-63e9-4212-b6df-524145cd6f09'::uuid, d.id, 1, 'Realiza composiciones y descomposiciones de números de dos dígitos en términos de la cantidad de "dieces" y de "unos" que los conforman.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select 'ba62d69e-0cc8-4157-90b1-8df4eac6921a'::uuid, d.id, 2, 'Encuentra parejas de números que al adicionarse dan como resultado otro número dado.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select '312d7547-0f1d-414b-9038-45301907f0ec'::uuid, d.id, 3, 'Halla los números correspondientes a tener "diez más" o "diez menos" que una cantidad determinada.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select '8ba0e5db-20d4-4259-9669-2fd1db1088f3'::uuid, d.id, 4, 'Emplea estrategias de cálculo como "el paso por el diez" para realizar adiciones o sustracciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('988d365c-63e9-4212-b6df-524145cd6f09'::uuid, 'multiple_choice', '¿Qué número tiene 5 decenas y 2 unidades?', '{"options":["52","25","502","7"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('988d365c-63e9-4212-b6df-524145cd6f09'::uuid, 'multiple_choice', 'El número 34 tiene:', '{"options":["3 decenas y 4 unidades","4 decenas y 3 unidades","34 decenas","3 unidades y 4 decenas"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('988d365c-63e9-4212-b6df-524145cd6f09'::uuid, 'multiple_choice', 'El número 70 tiene:', '{"options":["7 decenas y 0 unidades","0 decenas y 7 unidades","7 unidades","70 decenas"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ba62d69e-0cc8-4157-90b1-8df4eac6921a'::uuid, 'multiple_choice', '¿Cuál pareja suma 10?', '{"options":["6 y 4","6 y 3","5 y 6","8 y 3"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8ba0e5db-20d4-4259-9669-2fd1db1088f3'::uuid, 'multiple_choice', '¿Cuánto le falta a 8 para llegar a 10?', '{"options":["2","3","18","1"],"correctIndex":0,"operation":"8 + ? = 10"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8ba0e5db-20d4-4259-9669-2fd1db1088f3'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["13","12","14","11"],"correctIndex":0,"operation":"7 + 6 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('312d7547-0f1d-414b-9038-45301907f0ec'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["35","26","15","45"],"correctIndex":0,"operation":"25 + 10 = ?"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('312d7547-0f1d-414b-9038-45301907f0ec'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["30","39","50","20"],"correctIndex":0,"operation":"40 − 10 = ?"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('312d7547-0f1d-414b-9038-45301907f0ec'::uuid, 'multiple_choice', 'Diez más que 63 es:', '{"options":["73","64","53","630"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ba62d69e-0cc8-4157-90b1-8df4eac6921a'::uuid, 'multiple_choice', '¿Cuál pareja suma 20?', '{"options":["15 y 5","15 y 10","12 y 6","10 y 5"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 4: 4 evidencias, 9 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '3ec37b18-d971-4000-aef2-7bd6a38683eb'::uuid, d.id, 1, 'Identifica atributos que se pueden medir en los objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select '7f229cc9-1e5e-4727-9e65-35408b8839a1'::uuid, d.id, 2, 'Diferencia atributos medibles (longitud, masa, capacidad, duración, cantidad de elementos de una colección), en términos de los instrumentos y las unidades utilizadas para medirlos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select '12cbdb8e-edaa-4196-9937-715070806daf'::uuid, d.id, 3, 'Compara y ordena objetos de acuerdo con atributos como altura, peso, intensidades de color, entre otros y recorridos según la distancia de cada trayecto.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select 'c2446ac9-1b4f-491c-ae27-d006efff8e2f'::uuid, d.id, 4, 'Compara y ordena colecciones según la cantidad de elementos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c2446ac9-1b4f-491c-ae27-d006efff8e2f'::uuid, 'multiple_choice', '¿Cuál grupo tiene MÁS?', '{"options":["8 estrellas","6 estrellas","5 estrellas","3 estrellas"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('c2446ac9-1b4f-491c-ae27-d006efff8e2f'::uuid, 'multiple_choice', '¿Cuál grupo tiene MENOS?', '{"options":["2 flores","5 flores","7 flores","9 flores"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('3ec37b18-d971-4000-aef2-7bd6a38683eb'::uuid, 'multiple_choice', '¿Qué se puede medir de una cuerda?', '{"options":["Su largo","Su color","Su nombre","Su dueño"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('12cbdb8e-edaa-4196-9937-715070806daf'::uuid, 'multiple_choice', '¿Cuál es el MÁS CORTO?', '{"options":["Un clip","Un lápiz","Una regla","Una escoba"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('12cbdb8e-edaa-4196-9937-715070806daf'::uuid, 'multiple_choice', '¿Cuál pesa MÁS?', '{"options":["Un balde de agua","Un vaso de agua","Una cuchara de agua","Una gota de agua"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7f229cc9-1e5e-4727-9e65-35408b8839a1'::uuid, 'multiple_choice', '¿Con qué sabes cuánto PESA una fruta?', '{"options":["Con una balanza","Con una regla","Con un reloj","Con un vaso"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7f229cc9-1e5e-4727-9e65-35408b8839a1'::uuid, 'multiple_choice', '¿Con qué sabes cuánto DURA un juego?', '{"options":["Con un reloj","Con una regla","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7f229cc9-1e5e-4727-9e65-35408b8839a1'::uuid, 'multiple_choice', '¿Con qué sabes cuánta agua CABE en una jarra?', '{"options":["Con un vaso","Con una regla","Con un reloj","Con una balanza"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('12cbdb8e-edaa-4196-9937-715070806daf'::uuid, 'multiple_choice', '¿Quién caminó MÁS?', '{"options":["El que dio 30 pasos","El que dio 20 pasos","El que dio 10 pasos","El que dio 5 pasos"],"correctIndex":0}'::jsonb, 9);

-- ===== DBA 5: 3 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '87921d81-ecf0-46aa-8b63-32c52d5fb30d'::uuid, d.id, 1, 'Mide longitudes con diferentes instrumentos y expresa el resultado en unidades estandarizadas o no estandarizadas comunes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select '752b2288-50b6-443e-82e5-ce910f6d4552'::uuid, d.id, 2, 'Compara objetos a partir de su longitud, masa, capacidad y duración de eventos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select '1d70300f-2e73-4d42-89e7-24a1c02201d9'::uuid, d.id, 3, 'Toma decisiones a partir de las mediciones realizadas y de acuerdo con los requerimientos del problema.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('87921d81-ecf0-46aa-8b63-32c52d5fb30d'::uuid, 'multiple_choice', 'La mesa mide 4 cuartas. ¿Con qué la mediste?', '{"options":["Con la mano","Con un reloj","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('752b2288-50b6-443e-82e5-ce910f6d4552'::uuid, 'multiple_choice', '¿Cuál dura MÁS?', '{"options":["Una clase","Un parpadeo","Un estornudo","Un aplauso"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('752b2288-50b6-443e-82e5-ce910f6d4552'::uuid, 'multiple_choice', 'Dos cintas miden lo mismo. Entonces:', '{"options":["Son igual de largas","La primera es más larga","La segunda es más larga","No se pueden comparar"],"correctIndex":0,"operation":"8 clips y 8 clips"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('752b2288-50b6-443e-82e5-ce910f6d4552'::uuid, 'multiple_choice', '¿Cuál jarra tiene MÁS agua?', '{"options":["La de 7 vasos","La de 4 vasos","Las dos igual","No se sabe"],"correctIndex":0,"operation":"Una llena 4 vasos · Otra llena 7"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('87921d81-ecf0-46aa-8b63-32c52d5fb30d'::uuid, 'multiple_choice', '¿Cuántos clips más largo es el segundo lápiz?', '{"options":["2","8","3","1"],"correctIndex":0,"operation":"5 clips − 3 clips = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('1d70300f-2e73-4d42-89e7-24a1c02201d9'::uuid, 'multiple_choice', 'Necesitas 10 clips de cinta y tienes 6.', '{"options":["4","16","3","5"],"correctIndex":0,"operation":"6 + ? = 10"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('1d70300f-2e73-4d42-89e7-24a1c02201d9'::uuid, 'multiple_choice', '¿Cabe la caja en el estante?', '{"options":["No, la caja es más grande","Sí, y sobra espacio","Sí, entra justo","No se sabe"],"correctIndex":0,"operation":"Estante 6 cuartas · Caja 8 cuartas"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('87921d81-ecf0-46aa-8b63-32c52d5fb30d'::uuid, 'multiple_choice', 'Si mides el salón con pasos GRANDES, das:', '{"options":["Menos pasos","Más pasos","Los mismos pasos","Ningún paso"],"correctIndex":0}'::jsonb, 8);

-- ===== DBA 6: 4 evidencias, 9 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'fffb56f6-15c0-4727-b85b-92e8c2d26948'::uuid, d.id, 1, 'Crea, compone y descompone formas bidimensionales y tridimensionales, para ello utiliza plastilina, papel, palitos, cajas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '68aadad0-7284-49a2-90da-e0e3570e9875'::uuid, d.id, 2, 'Describe de forma verbal las cualidades y propiedades de un objeto relativas a su forma.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '0ba9b726-540e-4ba1-bede-11e963fcdbcb'::uuid, d.id, 3, 'Agrupa objetos de su entorno de acuerdo con las semejanzas y las diferencias en la forma y en el tamaño y explica el criterio que utiliza.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select 'ed981866-3f31-4b88-8163-b9f1689b19f0'::uuid, d.id, 4, 'Identifica objetos a partir de las descripciones verbales que hacen de sus características geométricas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('68aadad0-7284-49a2-90da-e0e3570e9875'::uuid, 'multiple_choice', '¿Cuántos lados tiene un triángulo?', '{"options":["3","4","5","1"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('68aadad0-7284-49a2-90da-e0e3570e9875'::uuid, 'multiple_choice', '¿Cuántos lados tiene un cuadrado?', '{"options":["4","3","5","6"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ed981866-3f31-4b88-8163-b9f1689b19f0'::uuid, 'multiple_choice', '¿Cuál figura es redonda?', '{"options":["Círculo","Triángulo","Cuadrado","Rectángulo"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ed981866-3f31-4b88-8163-b9f1689b19f0'::uuid, 'multiple_choice', 'Tiene 3 lados y 3 puntas. Es un:', '{"options":["Triángulo","Cuadrado","Círculo","Rectángulo"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ed981866-3f31-4b88-8163-b9f1689b19f0'::uuid, 'multiple_choice', 'Tiene 4 lados iguales y 4 puntas. Es un:', '{"options":["Cuadrado","Rectángulo","Triángulo","Círculo"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('68aadad0-7284-49a2-90da-e0e3570e9875'::uuid, 'multiple_choice', '¿Cuál de estas cosas tiene el borde CURVO?', '{"options":["Un plato","Una regla","Una mesa","Un libro"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('0ba9b726-540e-4ba1-bede-11e963fcdbcb'::uuid, 'multiple_choice', 'Una pelota tiene forma de:', '{"options":["Esfera","Cubo","Cilindro","Pirámide"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('0ba9b726-540e-4ba1-bede-11e963fcdbcb'::uuid, 'multiple_choice', 'Un dado tiene forma de:', '{"options":["Cubo","Esfera","Cono","Cilindro"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('0ba9b726-540e-4ba1-bede-11e963fcdbcb'::uuid, 'multiple_choice', 'Un vaso tiene forma de:', '{"options":["Cilindro","Cubo","Esfera","Pirámide"],"correctIndex":0}'::jsonb, 9);

-- ===== DBA 7: 4 evidencias, 7 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'fd5d3ea7-03bb-4b08-900b-fbcf1d3d5493'::uuid, d.id, 1, 'Utiliza representaciones como planos para ubicarse en el espacio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select 'd0f6b2ab-e5f9-4c0f-bfdf-0af3e969a107'::uuid, d.id, 2, 'Toma decisiones a partir de la ubicación espacial.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '9cb507b6-9537-4b5d-bd8b-e4a2066dda4f'::uuid, d.id, 3, 'Dibuja recorridos, para ello considera los ángulos y la lateralidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '36fbd6c7-e834-44bd-b572-1083c3a662f2'::uuid, d.id, 4, 'Compara distancias a partir de la observación del plano al estimar con pasos, baldosas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fd5d3ea7-03bb-4b08-900b-fbcf1d3d5493'::uuid, 'multiple_choice', 'El perro está DEBAJO de la mesa. Entonces la mesa está:', '{"options":["Encima del perro","Debajo del perro","Al lado del perro","Lejos del perro"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('36fbd6c7-e834-44bd-b572-1083c3a662f2'::uuid, 'multiple_choice', '¿Cuál camino es MÁS LARGO?', '{"options":["30 baldosas","20 baldosas","12 baldosas","8 baldosas"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('36fbd6c7-e834-44bd-b572-1083c3a662f2'::uuid, 'multiple_choice', '¿Cuál queda MÁS CERCA?', '{"options":["La tienda","El parque","Quedan igual","No se sabe"],"correctIndex":0,"operation":"Tienda: 10 pasos · Parque: 25 pasos"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('36fbd6c7-e834-44bd-b572-1083c3a662f2'::uuid, 'multiple_choice', 'Un camino de 3 cuadras es ___ que uno de 6 cuadras.', '{"options":["Más corto","Más largo","Igual de largo","Más ancho"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('9cb507b6-9537-4b5d-bd8b-e4a2066dda4f'::uuid, 'multiple_choice', 'Vas caminando y das media vuelta. Ahora vas:', '{"options":["De regreso","Para el mismo lado","Hacia arriba","Sin moverte"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fd5d3ea7-03bb-4b08-900b-fbcf1d3d5493'::uuid, 'multiple_choice', 'Estás en la puerta. El tablero está al frente. Para llegar:', '{"options":["Camino hacia el frente","Salgo del salón","Camino hacia atrás","Me quedo quieto"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('d0f6b2ab-e5f9-4c0f-bfdf-0af3e969a107'::uuid, 'multiple_choice', '¿Cuál indicación sirve para llegar a un lugar?', '{"options":["Camina 2 cuadras y gira","Camina un rato","Queda por ahí","Es una casa bonita"],"correctIndex":0}'::jsonb, 7);

-- ===== DBA 8: 3 evidencias, 7 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '59c4a2c5-6a8c-4249-a369-8fb4b3004685'::uuid, d.id, 1, 'Identifica y nombra diferencias entre objetos o grupos de objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select '5e8f4c54-8373-4e86-84ae-441d1b791bb5'::uuid, d.id, 2, 'Comunica las características identificadas y justifica las diferencias que encuentra.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select 'b4a83ce6-c1dd-4068-b3f7-c2ce769b679c'::uuid, d.id, 3, 'Establece relaciones de dependencia entre magnitudes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('59c4a2c5-6a8c-4249-a369-8fb4b3004685'::uuid, 'multiple_choice', 'Un vaso tenía 2 bolas. Ahora tiene 5. ¿Qué pasó?', '{"options":["Le pusieron más","Le quitaron","No cambió nada","Se hicieron grandes"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('59c4a2c5-6a8c-4249-a369-8fb4b3004685'::uuid, 'multiple_choice', 'Tenías 10 dulces. Ahora tienes 6. Entonces:', '{"options":["Te faltan 4","Te sobran 4","Te faltan 6","No cambió nada"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('5e8f4c54-8373-4e86-84ae-441d1b791bb5'::uuid, 'multiple_choice', 'Un grupo tiene 3 patos. El otro, 3 patos con sombrero.', '{"options":["Se diferencian en el sombrero","Se diferencian en la cantidad","No se diferencian","Se diferencian en el agua"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b4a83ce6-c1dd-4068-b3f7-c2ce769b679c'::uuid, 'multiple_choice', 'Sacas agua de la jarra para llenar vasos. En la jarra:', '{"options":["Queda menos agua","Queda más agua","Queda igual","El agua se congela"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b4a83ce6-c1dd-4068-b3f7-c2ce769b679c'::uuid, 'multiple_choice', 'Suben más personas al bus. Los puestos libres:', '{"options":["Son menos","Son más","Son los mismos","Se vuelven sillas"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b4a83ce6-c1dd-4068-b3f7-c2ce769b679c'::uuid, 'multiple_choice', 'Mientras más crece un árbol, su tronco es:', '{"options":["Más largo","Más corto","Igual de largo","Más delgado"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b4a83ce6-c1dd-4068-b3f7-c2ce769b679c'::uuid, 'multiple_choice', 'Si caminas más rápido, llegas:', '{"options":["Más temprano","Más tarde","A la misma hora","Nunca"],"correctIndex":0}'::jsonb, 7);

-- ===== DBA 9: 3 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, d.id, 1, 'Propone números que satisfacen una igualdad con sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select 'f241c3b4-dc00-4eb1-81bf-5a84d6a1908a'::uuid, d.id, 2, 'Describe las características de los números que deben ubicarse en una ecuación de tal manera que satisfaga la igualdad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select '866c0d6a-9ed2-495e-adf1-4bbea8fea9b4'::uuid, d.id, 3, 'Argumenta sobre el uso de la propiedad transitiva en un conjunto de igualdades.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","8","3","6"],"correctIndex":0,"operation":"6 = 2 + ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","16","5","3"],"correctIndex":0,"operation":"10 = ? + 6"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","5","6","3"],"correctIndex":0,"operation":"2 + 3 = 1 + ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["3","5","4","1"],"correctIndex":0,"operation":"4 + 1 = ? + 2"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","10","3","18"],"correctIndex":0,"operation":"5 + 5 = 8 + ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e57a863f-43bb-43c7-9506-81f5b53212e0'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","5","4","1"],"correctIndex":0,"operation":"7 − 2 = 3 + ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f241c3b4-dc00-4eb1-81bf-5a84d6a1908a'::uuid, 'multiple_choice', 'El signo = dice que los dos lados:', '{"options":["Valen igual","Se suman","Son distintos","Se restan"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('866c0d6a-9ed2-495e-adf1-4bbea8fea9b4'::uuid, 'multiple_choice', 'Entonces 3 + 4 también es igual a:', '{"options":["5 + 2","5 − 2","3 + 2","7 + 7"],"correctIndex":0,"operation":"3 + 4 = 7  y  7 = 5 + 2"}'::jsonb, 8);

-- ===== DBA 10: 4 evidencias, 8 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '597464fc-fb81-4e03-be9b-bc8992f6f860'::uuid, d.id, 1, 'Identifica en fichas u objetos reales los valores de la variable en estudio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '7d360cfe-5e44-4ce9-bdca-2eac00ec7983'::uuid, d.id, 2, 'Organiza los datos en tablas de conteo y/o en pictogramas sin escala.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '0a3d94d9-d0b9-4735-b861-9d921466ee7d'::uuid, d.id, 3, 'Lee la información presentada en tablas de conteo y/o pictogramas sin escala (1 a 1).' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, d.id, 4, 'Comunica los resultados respondiendo preguntas tales como: ¿cuántos hay en total?, ¿cuántos hay de cada dato?, ¿cuál es el dato que más se repite?, ¿cuál es el dato que menos aparece?' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('0a3d94d9-d0b9-4735-b861-9d921466ee7d'::uuid, 'multiple_choice', 'Cada helado es 1 niño. ¿Cuántos niños quieren chocolate?', '{"options":["4","3","5","8"],"correctIndex":0,"operation":"🍦🍦🍦🍦"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('0a3d94d9-d0b9-4735-b861-9d921466ee7d'::uuid, 'multiple_choice', 'Cada dibujo es 1 perro. ¿Cuántos perros hay?', '{"options":["6","1","12","3"],"correctIndex":0,"operation":"🐶🐶🐶🐶🐶🐶"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7d360cfe-5e44-4ce9-bdca-2eac00ec7983'::uuid, 'multiple_choice', 'En una tabla de conteo, las rayitas sirven para:', '{"options":["Contar cuántos hay","Dibujar","Medir el largo","Decir la hora"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, 'multiple_choice', '¿Cuál color ganó?', '{"options":["Azul","Rojo","Verde","Hubo empate"],"correctIndex":0,"operation":"Rojo 3 · Azul 5 · Verde 2"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, 'multiple_choice', '¿Cuál color tuvo MENOS votos?', '{"options":["Verde","Rojo","Azul","Todos igual"],"correctIndex":0,"operation":"Rojo 3 · Azul 5 · Verde 2"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, 'multiple_choice', '¿Cuántos niños votaron en total?', '{"options":["10","8","9","11"],"correctIndex":0,"operation":"3 + 5 + 2 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, 'multiple_choice', '¿Cuál fruta gusta más?', '{"options":["Mango y banano","Solo el mango","La papaya","Solo el banano"],"correctIndex":0,"operation":"Mango 7 · Banano 7 · Papaya 2"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4b54f763-03f3-4913-9d25-1cca7e227bc3'::uuid, 'multiple_choice', '¿Cuántos más prefieren mango que papaya?', '{"options":["5","9","4","2"],"correctIndex":0,"operation":"Mango 7 − Papaya 2 = ?"}'::jsonb, 8);

do $$
declare n_ev int; n_ex int; n_malas int; n_largas int;
begin
  select count(*) into n_ev from learning_evidences le join dbas d on d.id = le.dba_id
    join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1;
  select count(*) into n_ex from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1;
  select count(*) into n_malas from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1 and (jsonb_array_length(e.config->'options') <> 4
      or (select count(distinct v) from jsonb_array_elements_text(e.config->'options') v) <> 4);
  -- Un enunciado de más de 70 caracteres ya no lo lee un niño de primero: mide
  -- lectura, no matemáticas. Es la regla que motivó toda esta revisión, así que
  -- se comprueba en vez de confiar en que la respetamos.
  select count(*) into n_largas from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1 and length(e.prompt) > 70;
  if n_ev <> 39 then raise exception 'evidencias: % (esperadas 39)', n_ev; end if;
  if n_ex <> 88 then raise exception 'ejercicios: % (esperados 88)', n_ex; end if;
  if n_malas <> 0 then raise exception '% ejercicios sin 4 opciones distintas', n_malas; end if;
  if n_largas <> 0 then raise exception '% enunciados de más de 70 caracteres', n_largas; end if;
end $$;
