-- Revisión pedagógica del grado 1.
-- Las 39 evidencias del MEN no cambian. Cambia cómo está escrito cada
-- ejercicio (enunciado corto, opciones cortas, palabras de niño) y el ORDEN
-- dentro de cada lección: de lo concreto a lo abstracto.

-- El orden ya no lo manda el número de evidencia (una clasificación curricular,
-- no una rampa de dificultad) sino la posición dentro de la lección. La columna
-- pasa a llamarse por lo que de verdad significa.
do $$
begin
  if exists (select 1 from information_schema.columns
             where table_name = 'exercises' and column_name = 'order_in_evidence') then
    alter table exercises rename column order_in_evidence to order_in_lesson;
  end if;
end $$;

do $$
declare v_subject uuid;
begin
  select id into v_subject from subjects where slug = 'matematicas';
  delete from exercises where evidence_id in (
    select le.id from learning_evidences le
    join dbas d on d.id = le.dba_id
    where d.subject_id = v_subject and d.grade = 1);
  delete from learning_evidences where dba_id in (
    select id from dbas where subject_id = v_subject and grade = 1);
end $$;

-- ===== DBA 1: 5 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'f4a15b49-4854-46bf-8f50-73128df94605'::uuid, d.id, 1, 'Construye e interpreta representaciones pictóricas y diagramas para representar relaciones entre cantidades que se presentan en situaciones o fenómenos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select '02a02dd1-0e96-437a-b515-e4a52fac9918'::uuid, d.id, 2, 'Explica cómo y por qué es posible hacer una operación (suma o resta) en relación con los usos de los números y el contexto en el cual se presentan.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'f0d7804b-e884-44f7-829d-ff37c6649336'::uuid, d.id, 3, 'Reconoce en sus actuaciones cotidianas posibilidades de uso de los números y las operaciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'b7af7601-70a7-4e06-a4b8-b60c34102ca3'::uuid, d.id, 4, 'Interpreta y resuelve problemas de juntar, quitar y completar, que involucren la cantidad de elementos de una colección o la medida de magnitudes como longitud, peso, capacidad y duración.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into learning_evidences (id, dba_id, num, texto) select 'fadb076a-f626-4e3c-a623-e4d13cb91a5a'::uuid, d.id, 5, 'Utiliza las operaciones (suma y resta) para representar el cambio en una cantidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 1;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f0d7804b-e884-44f7-829d-ff37c6649336'::uuid, 'multiple_choice', '¿Cuál número dice CUÁNTOS hay?', '{"options":["5 manzanas","El piso 3","El bus 20","El teléfono 315"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f0d7804b-e884-44f7-829d-ff37c6649336'::uuid, 'multiple_choice', '¿Cuál número dice EN QUÉ PUESTO llegó?', '{"options":["Llegó de 2º","Tiene 2 perros","Mide 2 metros","Vive en la casa 2"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f0d7804b-e884-44f7-829d-ff37c6649336'::uuid, 'multiple_choice', '¿Cuál número dice CUÁNTO MIDE?', '{"options":["Mide 3 metros","Tengo 3 primos","Vivo en el piso 3","Soy el número 3"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f0d7804b-e884-44f7-829d-ff37c6649336'::uuid, 'multiple_choice', 'El número de tu casa sirve para:', '{"options":["Saber cuál casa es","Contar las casas","Medir la casa","Pesar la casa"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b7af7601-70a7-4e06-a4b8-b60c34102ca3'::uuid, 'multiple_choice', 'Ana tiene 3 bombas. Le regalan 2.', '{"options":["5","1","6","4"],"correctIndex":0,"operation":"3 + 2 = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b7af7601-70a7-4e06-a4b8-b60c34102ca3'::uuid, 'multiple_choice', 'Tienes 4 manzanas. Regalas 1.', '{"options":["3","5","2","4"],"correctIndex":0,"operation":"4 − 1 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b7af7601-70a7-4e06-a4b8-b60c34102ca3'::uuid, 'multiple_choice', 'Hay 6 galletas. Te comes 2.', '{"options":["4","8","3","5"],"correctIndex":0,"operation":"6 − 2 = ?"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b7af7601-70a7-4e06-a4b8-b60c34102ca3'::uuid, 'multiple_choice', 'Tengo 3 lápices. Quiero 7. ¿Cuántos faltan?', '{"options":["4","10","3","5"],"correctIndex":0,"operation":"3 + ? = 7"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fadb076a-f626-4e3c-a623-e4d13cb91a5a'::uuid, 'multiple_choice', 'Al bus se suben 3 niños. Para saber cuántos hay ahora:', '{"options":["Sumo","Resto","Cuento hacia atrás","No hago nada"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fadb076a-f626-4e3c-a623-e4d13cb91a5a'::uuid, 'multiple_choice', 'De la caja se pierden 4 crayolas. Para saber cuántas quedan:', '{"options":["Resto","Sumo","Cuento hacia adelante","No hago nada"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 2: 5 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '676527a6-3c8f-4556-898d-2878b5af0207'::uuid, d.id, 1, 'Realiza conteos (de uno en uno, de dos en dos, etc.) iniciando en cualquier número.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select 'e31a63ae-ef8a-4301-8ba5-1c469c8d0717'::uuid, d.id, 2, 'Determina la cantidad de elementos de una colección agrupándolos de 1 en 1, de 2 en 2, de 5 en 5.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '9e91831d-b6a5-4d00-91cb-2faaf8d96a7b'::uuid, d.id, 3, 'Describe y resuelve situaciones variadas con las operaciones de suma y resta en problemas cuya estructura puede ser a + b = ?, a + ? = c, o ? + b = c.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select '41006513-a1f5-40ea-bc6a-d46be4afc27b'::uuid, d.id, 4, 'Establece y argumenta conjeturas de los posibles resultados en una secuencia numérica.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into learning_evidences (id, dba_id, num, texto) select 'bdc4f64a-f985-4426-b297-d1d72223c31e'::uuid, d.id, 5, 'Utiliza las características del sistema decimal de numeración para crear estrategias de cálculo y estimación de sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 2;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('676527a6-3c8f-4556-898d-2878b5af0207'::uuid, 'multiple_choice', 'Cuenta de 1 en 1. ¿Qué sigue?', '{"options":["10","11","6","12"],"correctIndex":0,"operation":"7, 8, 9, ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('676527a6-3c8f-4556-898d-2878b5af0207'::uuid, 'multiple_choice', 'Cuenta de 2 en 2. ¿Qué sigue?', '{"options":["10","9","12","7"],"correctIndex":0,"operation":"4, 6, 8, ?"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e31a63ae-ef8a-4301-8ba5-1c469c8d0717'::uuid, 'multiple_choice', 'Hay 4 pares de medias. Cuéntalas de 2 en 2.', '{"options":["8","6","4","10"],"correctIndex":0,"operation":"2 + 2 + 2 + 2 = ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('e31a63ae-ef8a-4301-8ba5-1c469c8d0717'::uuid, 'multiple_choice', 'Tres manos abiertas. Cuenta de 5 en 5.', '{"options":["15","8","10","20"],"correctIndex":0,"operation":"5 + 5 + 5 = ?"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('9e91831d-b6a5-4d00-91cb-2faaf8d96a7b'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["8","2","7","9"],"correctIndex":0,"operation":"5 + 3 = ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('9e91831d-b6a5-4d00-91cb-2faaf8d96a7b'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["6","12","5","7"],"correctIndex":0,"operation":"9 − 3 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('9e91831d-b6a5-4d00-91cb-2faaf8d96a7b'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["7","11","6","8"],"correctIndex":0,"operation":"2 + ? = 9"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('9e91831d-b6a5-4d00-91cb-2faaf8d96a7b'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["6","14","5","7"],"correctIndex":0,"operation":"? + 4 = 10"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('bdc4f64a-f985-4426-b297-d1d72223c31e'::uuid, 'multiple_choice', '¿Cuánto le falta a 7 para llegar a 10?', '{"options":["3","4","17","2"],"correctIndex":0,"operation":"7 + ? = 10"}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('41006513-a1f5-40ea-bc6a-d46be4afc27b'::uuid, 'multiple_choice', 'En 2, 4, 6, 8... todos los números son:', '{"options":["Pares","Impares","Unos pares y otros no","Mayores que 10"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 3: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'b0b9e103-19cd-4c97-b6ba-a77dfafb6d74'::uuid, d.id, 1, 'Realiza composiciones y descomposiciones de números de dos dígitos en términos de la cantidad de "dieces" y de "unos" que los conforman.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select 'bd5b6b68-26e6-4b1b-bdc9-dce25ec85ed3'::uuid, d.id, 2, 'Encuentra parejas de números que al adicionarse dan como resultado otro número dado.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select '40ba20b7-5687-49c9-8a41-8dcc326d8945'::uuid, d.id, 3, 'Halla los números correspondientes a tener "diez más" o "diez menos" que una cantidad determinada.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into learning_evidences (id, dba_id, num, texto) select '115493a2-8060-4d2a-b305-47278894b5ca'::uuid, d.id, 4, 'Emplea estrategias de cálculo como "el paso por el diez" para realizar adiciones o sustracciones.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 3;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b0b9e103-19cd-4c97-b6ba-a77dfafb6d74'::uuid, 'multiple_choice', '¿Qué número tiene 5 decenas y 2 unidades?', '{"options":["52","25","502","7"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b0b9e103-19cd-4c97-b6ba-a77dfafb6d74'::uuid, 'multiple_choice', 'El número 34 tiene:', '{"options":["3 decenas y 4 unidades","4 decenas y 3 unidades","34 decenas","3 unidades y 4 decenas"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b0b9e103-19cd-4c97-b6ba-a77dfafb6d74'::uuid, 'multiple_choice', 'El número 70 tiene:', '{"options":["7 decenas y 0 unidades","0 decenas y 7 unidades","7 unidades","70 decenas"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('bd5b6b68-26e6-4b1b-bdc9-dce25ec85ed3'::uuid, 'multiple_choice', '¿Cuál pareja suma 10?', '{"options":["6 y 4","6 y 3","5 y 6","8 y 3"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('115493a2-8060-4d2a-b305-47278894b5ca'::uuid, 'multiple_choice', '¿Cuánto le falta a 8 para llegar a 10?', '{"options":["2","3","18","1"],"correctIndex":0,"operation":"8 + ? = 10"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('115493a2-8060-4d2a-b305-47278894b5ca'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["13","12","14","11"],"correctIndex":0,"operation":"7 + 6 = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('40ba20b7-5687-49c9-8a41-8dcc326d8945'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["35","26","15","45"],"correctIndex":0,"operation":"25 + 10 = ?"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('40ba20b7-5687-49c9-8a41-8dcc326d8945'::uuid, 'multiple_choice', '¿Cuánto es?', '{"options":["30","39","50","20"],"correctIndex":0,"operation":"40 − 10 = ?"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('40ba20b7-5687-49c9-8a41-8dcc326d8945'::uuid, 'multiple_choice', 'Diez más que 63 es:', '{"options":["73","64","53","630"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('bd5b6b68-26e6-4b1b-bdc9-dce25ec85ed3'::uuid, 'multiple_choice', '¿Cuál pareja suma 20?', '{"options":["15 y 5","15 y 10","12 y 6","10 y 5"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 4: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'cb377fb8-71a6-451b-8efb-83a5a4e0eaf0'::uuid, d.id, 1, 'Identifica atributos que se pueden medir en los objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select 'b2c91e7e-b4aa-49c5-ad86-2799b2226c5c'::uuid, d.id, 2, 'Diferencia atributos medibles (longitud, masa, capacidad, duración, cantidad de elementos de una colección), en términos de los instrumentos y las unidades utilizadas para medirlos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select 'f2624838-5ab2-4320-92f0-e731fe9fc155'::uuid, d.id, 3, 'Compara y ordena objetos de acuerdo con atributos como altura, peso, intensidades de color, entre otros y recorridos según la distancia de cada trayecto.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into learning_evidences (id, dba_id, num, texto) select '929e2f56-6846-4ebf-bf22-151568a38db0'::uuid, d.id, 4, 'Compara y ordena colecciones según la cantidad de elementos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 4;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('929e2f56-6846-4ebf-bf22-151568a38db0'::uuid, 'multiple_choice', '¿Cuál grupo tiene MÁS?', '{"options":["8 estrellas","6 estrellas","5 estrellas","3 estrellas"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('929e2f56-6846-4ebf-bf22-151568a38db0'::uuid, 'multiple_choice', '¿Cuál grupo tiene MENOS?', '{"options":["2 flores","5 flores","7 flores","9 flores"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('cb377fb8-71a6-451b-8efb-83a5a4e0eaf0'::uuid, 'multiple_choice', '¿Qué se puede medir de una cuerda?', '{"options":["Su largo","Su color","Su nombre","Su dueño"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('cb377fb8-71a6-451b-8efb-83a5a4e0eaf0'::uuid, 'multiple_choice', '¿Qué se puede medir de una caja de jugo?', '{"options":["Cuánto le cabe","Su marca","Su sabor","Su dibujo"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f2624838-5ab2-4320-92f0-e731fe9fc155'::uuid, 'multiple_choice', '¿Cuál es el MÁS CORTO?', '{"options":["Un clip","Un lápiz","Una regla","Una escoba"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f2624838-5ab2-4320-92f0-e731fe9fc155'::uuid, 'multiple_choice', '¿Cuál pesa MÁS?', '{"options":["Un balde de agua","Un vaso de agua","Una cuchara de agua","Una gota de agua"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b2c91e7e-b4aa-49c5-ad86-2799b2226c5c'::uuid, 'multiple_choice', '¿Con qué sabes cuánto PESA una fruta?', '{"options":["Con una balanza","Con una regla","Con un reloj","Con un vaso"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b2c91e7e-b4aa-49c5-ad86-2799b2226c5c'::uuid, 'multiple_choice', '¿Con qué sabes cuánto DURA un juego?', '{"options":["Con un reloj","Con una regla","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('b2c91e7e-b4aa-49c5-ad86-2799b2226c5c'::uuid, 'multiple_choice', '¿Con qué sabes cuánta agua CABE en una jarra?', '{"options":["Con un vaso","Con una regla","Con un reloj","Con una balanza"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('f2624838-5ab2-4320-92f0-e731fe9fc155'::uuid, 'multiple_choice', '¿Quién caminó MÁS?', '{"options":["El que dio 30 pasos","El que dio 20 pasos","El que dio 10 pasos","El que dio 5 pasos"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 5: 3 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '71c8e03e-f505-48d3-8f3d-87c7b26c76a0'::uuid, d.id, 1, 'Mide longitudes con diferentes instrumentos y expresa el resultado en unidades estandarizadas o no estandarizadas comunes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select 'fc2c4d62-4745-42ae-95c0-5d124958bdda'::uuid, d.id, 2, 'Compara objetos a partir de su longitud, masa, capacidad y duración de eventos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into learning_evidences (id, dba_id, num, texto) select '30f6bbf8-0f6e-46b1-a1a2-0a3756c0446f'::uuid, d.id, 3, 'Toma decisiones a partir de las mediciones realizadas y de acuerdo con los requerimientos del problema.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 5;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('71c8e03e-f505-48d3-8f3d-87c7b26c76a0'::uuid, 'multiple_choice', 'La mesa mide 4 cuartas. ¿Con qué la mediste?', '{"options":["Con la mano","Con un reloj","Con una balanza","Con un vaso"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fc2c4d62-4745-42ae-95c0-5d124958bdda'::uuid, 'multiple_choice', '¿Cuál dura MÁS?', '{"options":["Una clase","Un parpadeo","Un estornudo","Un aplauso"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fc2c4d62-4745-42ae-95c0-5d124958bdda'::uuid, 'multiple_choice', '¿Cuál pesa MENOS?', '{"options":["Una pluma","Un libro","Un zapato","Una piedra"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fc2c4d62-4745-42ae-95c0-5d124958bdda'::uuid, 'multiple_choice', 'Dos cintas miden lo mismo. Entonces:', '{"options":["Son igual de largas","La primera es más larga","La segunda es más larga","No se pueden comparar"],"correctIndex":0,"operation":"8 clips y 8 clips"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('fc2c4d62-4745-42ae-95c0-5d124958bdda'::uuid, 'multiple_choice', '¿Cuál jarra tiene MÁS agua?', '{"options":["La de 7 vasos","La de 4 vasos","Las dos igual","No se sabe"],"correctIndex":0,"operation":"Una llena 4 vasos · Otra llena 7"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('71c8e03e-f505-48d3-8f3d-87c7b26c76a0'::uuid, 'multiple_choice', '¿Cuántos clips más largo es el segundo lápiz?', '{"options":["2","8","3","1"],"correctIndex":0,"operation":"5 clips − 3 clips = ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('30f6bbf8-0f6e-46b1-a1a2-0a3756c0446f'::uuid, 'multiple_choice', 'Necesitas 10 clips de cinta y tienes 6.', '{"options":["4","16","3","5"],"correctIndex":0,"operation":"6 + ? = 10"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('30f6bbf8-0f6e-46b1-a1a2-0a3756c0446f'::uuid, 'multiple_choice', 'Tienes una cinta de 12 clips y usas 5.', '{"options":["7","17","6","8"],"correctIndex":0,"operation":"12 − 5 = ?"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('30f6bbf8-0f6e-46b1-a1a2-0a3756c0446f'::uuid, 'multiple_choice', '¿Cabe la caja en el estante?', '{"options":["No, la caja es más grande","Sí, y sobra espacio","Sí, entra justo","No se sabe"],"correctIndex":0,"operation":"Estante 6 cuartas · Caja 8 cuartas"}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('71c8e03e-f505-48d3-8f3d-87c7b26c76a0'::uuid, 'multiple_choice', 'Si mides el salón con pasos GRANDES, das:', '{"options":["Menos pasos","Más pasos","Los mismos pasos","Ningún paso"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 6: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '5c2397b0-dc93-451b-a47f-0b4c36fb557a'::uuid, d.id, 1, 'Crea, compone y descompone formas bidimensionales y tridimensionales, para ello utiliza plastilina, papel, palitos, cajas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '29127a13-1eed-466c-8caf-23a576be21e7'::uuid, d.id, 2, 'Describe de forma verbal las cualidades y propiedades de un objeto relativas a su forma.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '8e5293ab-cb6d-482b-9844-4ae2eac41825'::uuid, d.id, 3, 'Agrupa objetos de su entorno de acuerdo con las semejanzas y las diferencias en la forma y en el tamaño y explica el criterio que utiliza.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into learning_evidences (id, dba_id, num, texto) select '96821c68-f39e-4e75-a9a5-7b30619b4574'::uuid, d.id, 4, 'Identifica objetos a partir de las descripciones verbales que hacen de sus características geométricas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 6;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('29127a13-1eed-466c-8caf-23a576be21e7'::uuid, 'multiple_choice', '¿Cuántos lados tiene un triángulo?', '{"options":["3","4","5","1"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('5c2397b0-dc93-451b-a47f-0b4c36fb557a'::uuid, 'multiple_choice', '¿Con cuántos palitos haces un triángulo?', '{"options":["3","2","4","6"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('29127a13-1eed-466c-8caf-23a576be21e7'::uuid, 'multiple_choice', '¿Cuántos lados tiene un cuadrado?', '{"options":["4","3","5","6"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('96821c68-f39e-4e75-a9a5-7b30619b4574'::uuid, 'multiple_choice', '¿Cuál figura es redonda?', '{"options":["Círculo","Triángulo","Cuadrado","Rectángulo"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('96821c68-f39e-4e75-a9a5-7b30619b4574'::uuid, 'multiple_choice', 'Tiene 3 lados y 3 puntas. Es un:', '{"options":["Triángulo","Cuadrado","Círculo","Rectángulo"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('96821c68-f39e-4e75-a9a5-7b30619b4574'::uuid, 'multiple_choice', 'Tiene 4 lados iguales y 4 puntas. Es un:', '{"options":["Cuadrado","Rectángulo","Triángulo","Círculo"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('29127a13-1eed-466c-8caf-23a576be21e7'::uuid, 'multiple_choice', '¿Cuál de estas cosas tiene el borde CURVO?', '{"options":["Un plato","Una regla","Una mesa","Un libro"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8e5293ab-cb6d-482b-9844-4ae2eac41825'::uuid, 'multiple_choice', 'Una pelota tiene forma de:', '{"options":["Esfera","Cubo","Cilindro","Pirámide"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8e5293ab-cb6d-482b-9844-4ae2eac41825'::uuid, 'multiple_choice', 'Un dado tiene forma de:', '{"options":["Cubo","Esfera","Cono","Cilindro"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8e5293ab-cb6d-482b-9844-4ae2eac41825'::uuid, 'multiple_choice', 'Un vaso tiene forma de:', '{"options":["Cilindro","Cubo","Esfera","Pirámide"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 7: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '59ae0ed1-6ffc-4dc2-b626-1874a807593a'::uuid, d.id, 1, 'Utiliza representaciones como planos para ubicarse en el espacio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '68c6751c-aa51-4e39-8db7-deb6f609e52b'::uuid, d.id, 2, 'Toma decisiones a partir de la ubicación espacial.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '7c72c37a-04ac-429e-a036-7b9ee1c7441a'::uuid, d.id, 3, 'Dibuja recorridos, para ello considera los ángulos y la lateralidad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into learning_evidences (id, dba_id, num, texto) select '03e4fef3-d2c8-4bac-af2e-fe967d79751c'::uuid, d.id, 4, 'Compara distancias a partir de la observación del plano al estimar con pasos, baldosas, etc.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 7;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('59ae0ed1-6ffc-4dc2-b626-1874a807593a'::uuid, 'multiple_choice', 'El perro está DEBAJO de la mesa. Entonces la mesa está:', '{"options":["Encima del perro","Debajo del perro","Al lado del perro","Lejos del perro"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('03e4fef3-d2c8-4bac-af2e-fe967d79751c'::uuid, 'multiple_choice', '¿Cuál camino es MÁS LARGO?', '{"options":["30 baldosas","20 baldosas","12 baldosas","8 baldosas"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('03e4fef3-d2c8-4bac-af2e-fe967d79751c'::uuid, 'multiple_choice', '¿Cuál queda MÁS CERCA?', '{"options":["La tienda","El parque","Quedan igual","No se sabe"],"correctIndex":0,"operation":"Tienda: 10 pasos · Parque: 25 pasos"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('03e4fef3-d2c8-4bac-af2e-fe967d79751c'::uuid, 'multiple_choice', 'Un camino de 3 cuadras es ___ que uno de 6 cuadras.', '{"options":["Más corto","Más largo","Igual de largo","Más ancho"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7c72c37a-04ac-429e-a036-7b9ee1c7441a'::uuid, 'multiple_choice', 'El lápiz está a tu DERECHA. Para cogerlo estiras:', '{"options":["La mano derecha","La mano izquierda","Las dos manos","Ninguna mano"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('7c72c37a-04ac-429e-a036-7b9ee1c7441a'::uuid, 'multiple_choice', 'Vas caminando y das media vuelta. Ahora vas:', '{"options":["De regreso","Para el mismo lado","Hacia arriba","Sin moverte"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('59ae0ed1-6ffc-4dc2-b626-1874a807593a'::uuid, 'multiple_choice', 'En el plano, el colegio está debajo de tu casa. Para llegar:', '{"options":["Bajas","Subes","No te mueves","Das la vuelta"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('68c6751c-aa51-4e39-8db7-deb6f609e52b'::uuid, 'multiple_choice', 'El parque queda más lejos que la tienda. Llegar allá toma:', '{"options":["Más tiempo","Menos tiempo","El mismo tiempo","Nada de tiempo"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('59ae0ed1-6ffc-4dc2-b626-1874a807593a'::uuid, 'multiple_choice', 'Estás en la puerta. El tablero está al frente. Para llegar:', '{"options":["Camino hacia el frente","Salgo del salón","Camino hacia atrás","Me quedo quieto"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('68c6751c-aa51-4e39-8db7-deb6f609e52b'::uuid, 'multiple_choice', '¿Cuál indicación sirve para llegar a un lugar?', '{"options":["Camina 2 cuadras y gira","Camina un rato","Queda por ahí","Es una casa bonita"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 8: 3 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select '6e24816b-f958-407e-807a-1f733965d44a'::uuid, d.id, 1, 'Identifica y nombra diferencias entre objetos o grupos de objetos.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select '754f4d4a-3ca5-475a-93b9-29cb4cf02a3f'::uuid, d.id, 2, 'Comunica las características identificadas y justifica las diferencias que encuentra.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into learning_evidences (id, dba_id, num, texto) select '00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, d.id, 3, 'Establece relaciones de dependencia entre magnitudes.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 8;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('6e24816b-f958-407e-807a-1f733965d44a'::uuid, 'multiple_choice', 'Un vaso tenía 2 bolas. Ahora tiene 5. ¿Qué pasó?', '{"options":["Le pusieron más","Le quitaron","No cambió nada","Se hicieron grandes"],"correctIndex":0}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('6e24816b-f958-407e-807a-1f733965d44a'::uuid, 'multiple_choice', 'Tenías 10 dulces. Ahora tienes 6. Entonces:', '{"options":["Te faltan 4","Te sobran 4","Te faltan 6","No cambió nada"],"correctIndex":0}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('6e24816b-f958-407e-807a-1f733965d44a'::uuid, 'multiple_choice', 'Un grupo tiene 4 bolas y el otro también 4. Son:', '{"options":["Iguales en cantidad","Distintos en cantidad","Uno tiene más","No se sabe"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('754f4d4a-3ca5-475a-93b9-29cb4cf02a3f'::uuid, 'multiple_choice', 'Un grupo tiene 3 patos. El otro, 3 patos con sombrero.', '{"options":["Se diferencian en el sombrero","Se diferencian en la cantidad","No se diferencian","Se diferencian en el agua"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('754f4d4a-3ca5-475a-93b9-29cb4cf02a3f'::uuid, 'multiple_choice', '¿En qué se diferencian estos dos grupos?', '{"options":["Uno tiene más bolas","En el color","En la forma","En nada"],"correctIndex":0,"operation":"🔴🔴🔴   y   🔴🔴🔴🔴🔴"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, 'multiple_choice', 'Mientras más pesa algo, para levantarlo necesitas:', '{"options":["Más fuerza","Menos fuerza","La misma fuerza","Nada de fuerza"],"correctIndex":0}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, 'multiple_choice', 'Sacas agua de la jarra para llenar vasos. En la jarra:', '{"options":["Queda menos agua","Queda más agua","Queda igual","El agua se congela"],"correctIndex":0}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, 'multiple_choice', 'Suben más personas al bus. Los puestos libres:', '{"options":["Son menos","Son más","Son los mismos","Se vuelven sillas"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, 'multiple_choice', 'Mientras más crece un árbol, su tronco es:', '{"options":["Más largo","Más corto","Igual de largo","Más delgado"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('00e35b13-7eab-417c-82c2-151bd7df9992'::uuid, 'multiple_choice', 'Si caminas más rápido, llegas:', '{"options":["Más temprano","Más tarde","A la misma hora","Nunca"],"correctIndex":0}'::jsonb, 10);

-- ===== DBA 9: 3 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, d.id, 1, 'Propone números que satisfacen una igualdad con sumas y restas.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select '2e436e57-7937-4cf5-961c-48070bc92caa'::uuid, d.id, 2, 'Describe las características de los números que deben ubicarse en una ecuación de tal manera que satisfaga la igualdad.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into learning_evidences (id, dba_id, num, texto) select '8e4e3d8f-e1ed-40b6-bffc-a1c03dd0a5c7'::uuid, d.id, 3, 'Argumenta sobre el uso de la propiedad transitiva en un conjunto de igualdades.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 9;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","8","3","6"],"correctIndex":0,"operation":"6 = 2 + ?"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","16","5","3"],"correctIndex":0,"operation":"10 = ? + 6"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","5","6","3"],"correctIndex":0,"operation":"2 + 3 = 1 + ?"}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["3","5","4","1"],"correctIndex":0,"operation":"4 + 1 = ? + 2"}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","10","3","18"],"correctIndex":0,"operation":"5 + 5 = 8 + ?"}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["2","5","4","1"],"correctIndex":0,"operation":"7 − 2 = 3 + ?"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('aa260b75-ddfc-44ad-b7f0-5953bd6eb739'::uuid, 'multiple_choice', '¿Qué número falta?', '{"options":["4","5","2","11"],"correctIndex":0,"operation":"8 − 3 = ? + 1"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('2e436e57-7937-4cf5-961c-48070bc92caa'::uuid, 'multiple_choice', 'El signo = dice que los dos lados:', '{"options":["Valen igual","Se suman","Son distintos","Se restan"],"correctIndex":0}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('2e436e57-7937-4cf5-961c-48070bc92caa'::uuid, 'multiple_choice', 'En 4 + ? = 4 + 6, el número que falta es:', '{"options":["Igual a 6","Mayor que 6","Menor que 6","Cualquiera"],"correctIndex":0}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8e4e3d8f-e1ed-40b6-bffc-a1c03dd0a5c7'::uuid, 'multiple_choice', 'Entonces 3 + 4 también es igual a:', '{"options":["5 + 2","5 − 2","3 + 2","7 + 7"],"correctIndex":0,"operation":"3 + 4 = 7  y  7 = 5 + 2"}'::jsonb, 10);

-- ===== DBA 10: 4 evidencias, 10 ejercicios =====
insert into learning_evidences (id, dba_id, num, texto) select 'ebeca162-0a9f-45d1-8473-d588d1d211f7'::uuid, d.id, 1, 'Identifica en fichas u objetos reales los valores de la variable en estudio.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '04ca7e10-5d3f-47e6-8d6c-962b25d420fe'::uuid, d.id, 2, 'Organiza los datos en tablas de conteo y/o en pictogramas sin escala.' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '4dec3066-5baf-491e-ab69-b0fcda8729ed'::uuid, d.id, 3, 'Lee la información presentada en tablas de conteo y/o pictogramas sin escala (1 a 1).' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into learning_evidences (id, dba_id, num, texto) select '8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, d.id, 4, 'Comunica los resultados respondiendo preguntas tales como: ¿cuántos hay en total?, ¿cuántos hay de cada dato?, ¿cuál es el dato que más se repite?, ¿cuál es el dato que menos aparece?' from dbas d join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1 and d.num = 10;
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4dec3066-5baf-491e-ab69-b0fcda8729ed'::uuid, 'multiple_choice', 'Cada helado es 1 niño. ¿Cuántos niños quieren chocolate?', '{"options":["4","3","5","8"],"correctIndex":0,"operation":"🍦🍦🍦🍦"}'::jsonb, 1);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('4dec3066-5baf-491e-ab69-b0fcda8729ed'::uuid, 'multiple_choice', 'Cada dibujo es 1 perro. ¿Cuántos perros hay?', '{"options":["6","1","12","3"],"correctIndex":0,"operation":"🐶🐶🐶🐶🐶🐶"}'::jsonb, 2);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('04ca7e10-5d3f-47e6-8d6c-962b25d420fe'::uuid, 'multiple_choice', 'En una tabla de conteo, las rayitas sirven para:', '{"options":["Contar cuántos hay","Dibujar","Medir el largo","Decir la hora"],"correctIndex":0}'::jsonb, 3);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ebeca162-0a9f-45d1-8473-d588d1d211f7'::uuid, 'multiple_choice', 'En una encuesta de mascota favorita se cuenta:', '{"options":["Cuántos eligen cada una","El tamaño de la mascota","El nombre de los niños","La edad de los niños"],"correctIndex":0}'::jsonb, 4);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('ebeca162-0a9f-45d1-8473-d588d1d211f7'::uuid, 'multiple_choice', 'Para saber la fruta preferida del salón, preguntas a:', '{"options":["Todos los niños","Solo a tu amigo","Solo a la profe","A nadie"],"correctIndex":0}'::jsonb, 5);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, 'multiple_choice', '¿Cuál color ganó?', '{"options":["Azul","Rojo","Verde","Hubo empate"],"correctIndex":0,"operation":"Rojo 3 · Azul 5 · Verde 2"}'::jsonb, 6);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, 'multiple_choice', '¿Cuál color tuvo MENOS votos?', '{"options":["Verde","Rojo","Azul","Todos igual"],"correctIndex":0,"operation":"Rojo 3 · Azul 5 · Verde 2"}'::jsonb, 7);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, 'multiple_choice', '¿Cuántos niños votaron en total?', '{"options":["10","8","9","11"],"correctIndex":0,"operation":"3 + 5 + 2 = ?"}'::jsonb, 8);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, 'multiple_choice', '¿Cuál fruta gusta más?', '{"options":["Mango y banano","Solo el mango","La papaya","Solo el banano"],"correctIndex":0,"operation":"Mango 7 · Banano 7 · Papaya 2"}'::jsonb, 9);
insert into exercises (evidence_id, type, prompt, config, order_in_lesson) values ('8d3a61cb-1937-4aab-8d81-8c08a72e7707'::uuid, 'multiple_choice', '¿Cuántos más prefieren mango que papaya?', '{"options":["5","9","4","2"],"correctIndex":0,"operation":"Mango 7 − Papaya 2 = ?"}'::jsonb, 10);

do $$
declare n_ev int; n_ex int; n_malas int; n_largas int; n_desparejos int;
begin
  -- Toda lección tiene que tener exactamente 10 ejercicios: es lo que hace que
  -- la escala de estrellas signifique lo mismo en todos los temas.
  select count(*) into n_desparejos from (
    select d.num from dbas d
      join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
      join learning_evidences le on le.dba_id = d.id
      join exercises e on e.evidence_id = le.id
    where d.grade = 1 group by d.num having count(e.id) <> 10) t;
  select count(*) into n_ev from learning_evidences le join dbas d on d.id = le.dba_id
    join subjects s on s.id = d.subject_id and s.slug = 'matematicas' where d.grade = 1;
  select count(*) into n_ex from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1;
  select count(*) into n_malas from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1 and (jsonb_array_length(e.config->'options') <> 4
      or (select count(distinct v) from jsonb_array_elements_text(e.config->'options') v) <> 4);
  -- Un enunciado de más de 70 caracteres ya no lo lee un niño de primero: mide
  -- lectura, no matemáticas. Es la regla que motivó toda esta revisión, así que
  -- se comprueba en vez de confiar en que la respetamos.
  select count(*) into n_largas from exercises e join learning_evidences le on le.id = e.evidence_id
    join dbas d on d.id = le.dba_id join subjects s on s.id = d.subject_id and s.slug = 'matematicas'
    where d.grade = 1 and length(e.prompt) > 70;
  if n_ev <> 39 then raise exception 'evidencias: % (esperadas 39)', n_ev; end if;
  if n_ex <> 100 then raise exception 'ejercicios: % (esperados 100)', n_ex; end if;
  if n_malas <> 0 then raise exception '% ejercicios sin 4 opciones distintas', n_malas; end if;
  if n_largas <> 0 then raise exception '% enunciados de más de 70 caracteres', n_largas; end if;
  if n_desparejos <> 0 then raise exception '% temas que no tienen 10 ejercicios', n_desparejos; end if;
end $$;
